apiVersion: v1
kind: Pod
metadata:
  name: tomcat-nginx
  namespace: devenv
  labels:
    app: tomcat
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      resources:
        limits:
          cpu: "400m"
          memory: "250Mi"
        requests:
          cpu: "400m"
          memory: "250Mi" 

