apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tomcat
  namespace: devenv
spec:
  selector: 
   matchLabels: 
     app: tomcat
  template:
    metadata:
      name: tomcat-nginx
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat
          image: krishna123456/tomcat:1.11.111
