apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  nodeSelector:
    size: large
  volumes:
    - name: "jenkins-data"
      hostPath:
        path: "/root/jenkins"
  containers:
    - name: jenkins
      image: jenkins/jenkins:lts
      volumeMounts:
        - mountPath: "/var/jenkins_home"
          name: "jenkins-data"
